package actions

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"time"
)

func init() {
	Register(&LogConfigureShippingAction{})
	Register(&LogShippingStatusAction{})
	Register(&LogDisableShippingAction{})
	Register(&LogInstallShipperAction{})
}

// ═══════════════════════════════════════════════════════════════
// Log shipping (journald → Loki via Fluent Bit).
//
// Nexus CONFIGURES a log shipper; it is not a log platform. This file holds the
// config GENERATOR — the "B v2" pipeline validated against a real Loki 3.x during
// the POC: a human-readable MESSAGE line + low-cardinality labels + structured
// metadata (ident/pid). Install/service/sudoers wiring lands in later increments.
// ═══════════════════════════════════════════════════════════════

const (
	fluentBitConfigPath = "/etc/fluent-bit/nexus.yaml"
	fluentBitHTTPPort   = 2020 // local health endpoint polled by logs.shipping_status
)

// LokiShipParams are the deployment-specific settings. Auth/secrets support (via a
// root-only env-file) is a later increment; this covers the no-auth, trusted-LAN
// case (matches the current deployment). Host/port/tenant are validated and baked
// into the config; they are NON-secret.
type LokiShipParams struct {
	Host   string // Loki host or IPv4
	Port   string // Loki port (numeric)
	TLS    bool   // https to Loki
	Tenant string // optional X-Scope-OrgID (empty = single-tenant)
}

var (
	lokiHostRe   = regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9.\-]{0,251}[a-zA-Z0-9])?$`)
	lokiPortRe   = regexp.MustCompile(`^[0-9]{1,5}$`)
	lokiTenantRe = regexp.MustCompile(`^[a-zA-Z0-9._\-]{0,64}$`)
)

// validateLokiShipParams rejects anything that could break the YAML or inject a
// second directive. Kept strict: host = hostname/IPv4 charset, port = digits,
// tenant = safe charset.
func validateLokiShipParams(p LokiShipParams) error {
	if !lokiHostRe.MatchString(p.Host) {
		return fmt.Errorf("invalid loki host %q", p.Host)
	}
	if !lokiPortRe.MatchString(p.Port) {
		return fmt.Errorf("invalid loki port %q (digits only)", p.Port)
	}
	if n := len(p.Port); n == 0 {
		return fmt.Errorf("loki port required")
	}
	if !lokiTenantRe.MatchString(p.Tenant) {
		return fmt.Errorf("invalid loki tenant %q", p.Tenant)
	}
	return nil
}

// buildFluentBitConfig renders the validated "B v2" pipeline. Host/port/tls/tenant
// are baked in (validated, non-secret). The journald noise is dropped by the
// record_modifier allowlist; the loki output turns MESSAGE into the raw line
// (drop_single_key: raw) with low-cardinality labels and ident/pid as structured
// metadata. Proven against a real Loki 3.x during the POC.
func buildFluentBitConfig(p LokiShipParams) string {
	var b strings.Builder
	b.WriteString(`# Generated by Nexus — journald -> Loki (readable line + structured metadata).
# Do not edit by hand: overwritten on the next logs.configure_shipping.
service:
  flush: 5
  log_level: info
  http_server: on
  http_listen: 127.0.0.1
  http_port: 2020
  health_check: on

pipeline:
  inputs:
    - name: systemd
      tag: journal.*
      read_from_tail: on
      strip_underscores: on

  filters:
    - name: record_modifier
      match: '*'
      Allowlist_key: MESSAGE
      Allowlist_key: HOSTNAME
      Allowlist_key: MACHINE_ID
      Allowlist_key: SYSTEMD_UNIT
      Allowlist_key: PRIORITY
      Allowlist_key: SYSLOG_IDENTIFIER
      Allowlist_key: PID

  outputs:
    - name: loki
      match: '*'
`)
	fmt.Fprintf(&b, "      host: %s\n      port: %s\n", p.Host, p.Port)
	if p.TLS {
		b.WriteString("      tls: on\n      tls.verify: on\n")
	} else {
		b.WriteString("      tls: off\n")
	}
	if p.Tenant != "" {
		fmt.Fprintf(&b, "      tenant_id: %s\n", p.Tenant)
	}
	b.WriteString(`      labels: job=nexus-fleet, host=$HOSTNAME, machine_id=$MACHINE_ID, unit=$SYSTEMD_UNIT, level=$PRIORITY
      structured_metadata: ident=$SYSLOG_IDENTIFIER, pid=$PID
      remove_keys: HOSTNAME, MACHINE_ID, SYSTEMD_UNIT, PRIORITY, SYSLOG_IDENTIFIER, PID
      drop_single_key: raw
      line_format: json
`)
	return b.String()
}

const (
	fluentBitBinary     = "/opt/fluent-bit/bin/fluent-bit"
	fluentBitService    = "fluent-bit"
	fluentBitDropinPath = "/etc/systemd/system/fluent-bit.service.d/10-nexus.conf"
)

// fluentBitDropin overrides the packaged unit's ExecStart so Fluent Bit runs with
// the Nexus-managed config (same pattern as the sshd drop-in: we don't fight the
// package default, we point it at our file).
const fluentBitDropin = `# Generated by Nexus — run Fluent Bit with the Nexus-managed config.
[Service]
ExecStart=
ExecStart=` + fluentBitBinary + ` -c ` + fluentBitConfigPath + `
`

func paramsToLokiShip(params map[string]interface{}) LokiShipParams {
	tls, _ := params["tls"].(bool)
	return LokiShipParams{
		Host:   paramStr(params, "loki_host", ""),
		Port:   paramStr(params, "loki_port", "3100"),
		TLS:    tls,
		Tenant: paramStr(params, "tenant", ""),
	}
}

type LogConfigureShippingAction struct{}

func (a *LogConfigureShippingAction) ID() string         { return "logs.configure_shipping" }
func (a *LogConfigureShippingAction) Capability() string { return "monitoring" }

func (a *LogConfigureShippingAction) Validate(params map[string]interface{}) error {
	return validateLokiShipParams(paramsToLokiShip(params))
}

func (a *LogConfigureShippingAction) Execute(params map[string]interface{}) (interface{}, error) {
	p := paramsToLokiShip(params)
	if err := validateLokiShipParams(p); err != nil {
		return nil, err
	}
	cfg := buildFluentBitConfig(p)

	if isDryRun(params) {
		return map[string]interface{}{
			"dry_run":     true,
			"config_path": fluentBitConfigPath,
			"content":     cfg,
		}, nil
	}

	if !fileExists(fluentBitBinary) {
		return nil, fmt.Errorf("fluent-bit not installed (%s missing) — provision it first", fluentBitBinary)
	}

	// 1. Nexus-managed config.
	if err := installRootFile(cfg, "sec-flbconf-*.tmp", fluentBitConfigPath); err != nil {
		return nil, err
	}
	// 2. systemd drop-in → the service runs our config (install -D creates the .d dir).
	if err := installRootFileD(fluentBitDropin, "sec-flbdropin-*.tmp", fluentBitDropinPath); err != nil {
		return nil, err
	}
	// 3. reload the unit, then enable + (re)start via the compiled privhelper.
	if err := sudoRun("/usr/bin/systemctl", "daemon-reload"); err != nil {
		return nil, fmt.Errorf("daemon-reload: %w", err)
	}
	if err := sudoRun(nexusAgentBin, "privhelper", "svc", "enable", fluentBitService); err != nil {
		return nil, fmt.Errorf("enable %s: %w", fluentBitService, err)
	}
	if err := sudoRun(nexusAgentBin, "privhelper", "svc", "restart", fluentBitService); err != nil {
		return nil, fmt.Errorf("restart %s: %w", fluentBitService, err)
	}

	return map[string]interface{}{
		"configured":  true,
		"config_path": fluentBitConfigPath,
		"loki":        p.Host + ":" + p.Port,
		"active":      systemctlActive(fluentBitService),
	}, nil
}

// installRootFileD is installRootFile with `install -D` (creates parent dirs) —
// needed for the systemd drop-in under /etc/systemd/system/<unit>.d/.
func installRootFileD(content, tmpPattern, dest string) error {
	tmp, err := os.CreateTemp("/var/lib/nexus-agent", tmpPattern)
	if err != nil {
		return fmt.Errorf("tempfile: %w", err)
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return fmt.Errorf("write tempfile: %w", err)
	}
	tmp.Close()
	if err := sudoRun("/usr/bin/install", "-D", "-m", "644", "-o", "root", "-g", "root", tmp.Name(), dest); err != nil {
		return fmt.Errorf("install -D %s: %w", dest, err)
	}
	return nil
}

// ── logs.shipping_status (read-only) ──

type LogShippingStatusAction struct{}

func (a *LogShippingStatusAction) ID() string                              { return "logs.shipping_status" }
func (a *LogShippingStatusAction) Capability() string                      { return "monitoring" }
func (a *LogShippingStatusAction) Validate(_ map[string]interface{}) error { return nil }

func (a *LogShippingStatusAction) Execute(_ map[string]interface{}) (interface{}, error) {
	return map[string]interface{}{
		"installed":      fileExists(fluentBitBinary),
		"config_present": fileExists(fluentBitConfigPath),
		"managed":        fileExists(fluentBitDropinPath), // Nexus drop-in in place
		"service_active": systemctlActive(fluentBitService),
		"health_ok":      fluentBitHealthy(),
		"http_port":      fluentBitHTTPPort,
	}, nil
}

// fluentBitHealthy polls Fluent Bit's local health endpoint (127.0.0.1:2020,
// enabled by the generated config). 200 = up. Localhost only, short timeout.
func fluentBitHealthy() bool {
	client := &http.Client{Timeout: 2 * time.Second}
	resp, err := client.Get(fmt.Sprintf("http://127.0.0.1:%d/api/v1/health", fluentBitHTTPPort))
	if err != nil {
		return false
	}
	defer resp.Body.Close()
	return resp.StatusCode == http.StatusOK
}

// ── logs.disable_shipping (mutation) ──

type LogDisableShippingAction struct{}

func (a *LogDisableShippingAction) ID() string                              { return "logs.disable_shipping" }
func (a *LogDisableShippingAction) Capability() string                      { return "monitoring" }
func (a *LogDisableShippingAction) Validate(_ map[string]interface{}) error { return nil }

func (a *LogDisableShippingAction) Execute(_ map[string]interface{}) (interface{}, error) {
	// Best-effort teardown (idempotent): stop/disable the service, drop the Nexus
	// config + drop-in, then reload so the unit reverts to its packaged default.
	_ = sudoRun(nexusAgentBin, "privhelper", "svc", "disable", fluentBitService)
	_ = sudoRun(nexusAgentBin, "privhelper", "svc", "stop", fluentBitService)
	_ = sudoRun("/bin/rm", "-f", fluentBitDropinPath)
	_ = sudoRun("/bin/rm", "-f", fluentBitConfigPath)
	if err := sudoRun("/usr/bin/systemctl", "daemon-reload"); err != nil {
		return nil, fmt.Errorf("daemon-reload: %w", err)
	}
	return map[string]interface{}{
		"disabled":       true,
		"service_active": systemctlActive(fluentBitService),
	}, nil
}

// ── logs.install_shipper (mutation) — GPG-pinned apt repo install ──

const (
	fluentBitKeyURL         = "https://packages.fluentbit.io/fluentbit.key"
	fluentBitKeyFingerprint = "C3C0A28534B9293EAF51FABD9F9DDC083888C1CD" // pinned: current signing key (>=1.8.15/1.9)
	fluentBitKeyringPath    = "/usr/share/keyrings/fluentbit-keyring.gpg"
	fluentBitRepoPath       = "/etc/apt/sources.list.d/fluent-bit.list"
)

type LogInstallShipperAction struct{}

func (a *LogInstallShipperAction) ID() string                              { return "logs.install_shipper" }
func (a *LogInstallShipperAction) Capability() string                      { return "monitoring" }
func (a *LogInstallShipperAction) Validate(_ map[string]interface{}) error { return nil }

func (a *LogInstallShipperAction) Execute(_ map[string]interface{}) (interface{}, error) {
	if fileExists(fluentBitBinary) {
		return map[string]interface{}{"already_installed": true, "binary": fluentBitBinary}, nil
	}
	distroID := osReleaseField("ID")
	codename := osReleaseField("VERSION_CODENAME")
	if (distroID != "ubuntu" && distroID != "debian") || codename == "" {
		return nil, fmt.Errorf("auto-install supports ubuntu/debian only (got ID=%q codename=%q) — install fluent-bit manually", distroID, codename)
	}

	// 1. Fetch the repo signing key over HTTPS.
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(fluentBitKeyURL)
	if err != nil {
		return nil, fmt.Errorf("fetch fluent-bit key: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("fetch fluent-bit key: HTTP %d", resp.StatusCode)
	}
	armored, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return nil, fmt.Errorf("read key: %w", err)
	}

	// 2. AUTHORITY: the fetched key's fingerprint MUST equal the pinned one, else
	// abort — we never trust a key we did not pin (TLS alone is not enough).
	fpr, err := gpgFingerprint(armored)
	if err != nil {
		return nil, err
	}
	if !strings.EqualFold(strings.TrimSpace(fpr), fluentBitKeyFingerprint) {
		return nil, fmt.Errorf("fluent-bit key fingerprint mismatch: pinned %s, got %s — refusing install", fluentBitKeyFingerprint, fpr)
	}

	// 3. Dearmor + install the keyring (root:root 0644).
	dearmored, err := gpgDearmor(armored)
	if err != nil {
		return nil, err
	}
	if err := installRootBytes(dearmored, "sec-flbkey-*.tmp", fluentBitKeyringPath, "644"); err != nil {
		return nil, err
	}

	// 4. Signed-by apt source for this distro/codename.
	repo := fmt.Sprintf("deb [signed-by=%s] https://packages.fluentbit.io/%s/%s %s main\n",
		fluentBitKeyringPath, distroID, codename, codename)
	if err := installRootFile(repo, "sec-flbrepo-*.tmp", fluentBitRepoPath); err != nil {
		return nil, err
	}

	// 5. apt update + install (apt install carries the NOEXEC backstop in sudoers).
	if err := sudoRun("/usr/bin/apt-get", "update"); err != nil {
		return nil, fmt.Errorf("apt-get update: %w", err)
	}
	if err := sudoRun(nexusAgentBin, "privhelper", "pkg", "install", "fluent-bit"); err != nil {
		return nil, fmt.Errorf("install fluent-bit: %w", err)
	}
	return map[string]interface{}{"installed": fileExists(fluentBitBinary), "binary": fluentBitBinary, "codename": codename}, nil
}

// osReleaseField reads KEY=value from /etc/os-release (quotes stripped).
func osReleaseField(key string) string {
	data, err := os.ReadFile("/etc/os-release")
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, key+"=") {
			return strings.Trim(strings.TrimPrefix(line, key+"="), `"`)
		}
	}
	return ""
}

// gpgFingerprint returns the primary-key fingerprint of an ASCII-armored key,
// parsed from `gpg --show-keys --with-colons` (the `fpr:` record). No keyring is
// touched (parse-only).
func gpgFingerprint(armored []byte) (string, error) {
	cmd := exec.Command("gpg", "--show-keys", "--with-colons")
	cmd.Stdin = bytes.NewReader(armored)
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("gpg --show-keys: %w", err)
	}
	for _, line := range strings.Split(string(out), "\n") {
		if strings.HasPrefix(line, "fpr:") {
			f := strings.Split(line, ":")
			if len(f) >= 10 && f[9] != "" {
				return f[9], nil
			}
		}
	}
	return "", fmt.Errorf("no fingerprint found in key")
}

func gpgDearmor(armored []byte) ([]byte, error) {
	cmd := exec.Command("gpg", "--dearmor")
	cmd.Stdin = bytes.NewReader(armored)
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("gpg --dearmor: %w", err)
	}
	return out, nil
}

// installRootBytes is installRootFile for binary content (the dearmored keyring).
func installRootBytes(content []byte, tmpPattern, dest, mode string) error {
	tmp, err := os.CreateTemp("/var/lib/nexus-agent", tmpPattern)
	if err != nil {
		return fmt.Errorf("tempfile: %w", err)
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return fmt.Errorf("write tempfile: %w", err)
	}
	tmp.Close()
	if err := sudoRun("/usr/bin/install", "-m", mode, "-o", "root", "-g", "root", tmp.Name(), dest); err != nil {
		return fmt.Errorf("install %s: %w", dest, err)
	}
	return nil
}
