package actions

import (
	"fmt"
	"regexp"
	"strings"
)

// ═══════════════════════════════════════════════════════════════
// Log shipping (journald → Loki via Fluent Bit).
//
// Nexus CONFIGURES a log shipper; it is not a log platform. This file holds the
// config GENERATOR — the "B v2" pipeline validated against a real Loki 3.x during
// the POC: a human-readable MESSAGE line + low-cardinality labels + structured
// metadata (ident/pid). Install/service/sudoers wiring lands in later increments.
// ═══════════════════════════════════════════════════════════════

const (
	fluentBitConfigPath = "/etc/fluent-bit/nexus.yaml"
	fluentBitHTTPPort   = 2020 // local health endpoint polled by logs.shipping_status
)

// LokiShipParams are the deployment-specific settings. Auth/secrets support (via a
// root-only env-file) is a later increment; this covers the no-auth, trusted-LAN
// case (matches the current deployment). Host/port/tenant are validated and baked
// into the config; they are NON-secret.
type LokiShipParams struct {
	Host   string // Loki host or IPv4
	Port   string // Loki port (numeric)
	TLS    bool   // https to Loki
	Tenant string // optional X-Scope-OrgID (empty = single-tenant)
}

var (
	lokiHostRe   = regexp.MustCompile(`^[a-zA-Z0-9]([a-zA-Z0-9.\-]{0,251}[a-zA-Z0-9])?$`)
	lokiPortRe   = regexp.MustCompile(`^[0-9]{1,5}$`)
	lokiTenantRe = regexp.MustCompile(`^[a-zA-Z0-9._\-]{0,64}$`)
)

// validateLokiShipParams rejects anything that could break the YAML or inject a
// second directive. Kept strict: host = hostname/IPv4 charset, port = digits,
// tenant = safe charset.
func validateLokiShipParams(p LokiShipParams) error {
	if !lokiHostRe.MatchString(p.Host) {
		return fmt.Errorf("invalid loki host %q", p.Host)
	}
	if !lokiPortRe.MatchString(p.Port) {
		return fmt.Errorf("invalid loki port %q (digits only)", p.Port)
	}
	if n := len(p.Port); n == 0 {
		return fmt.Errorf("loki port required")
	}
	if !lokiTenantRe.MatchString(p.Tenant) {
		return fmt.Errorf("invalid loki tenant %q", p.Tenant)
	}
	return nil
}

// buildFluentBitConfig renders the validated "B v2" pipeline. Host/port/tls/tenant
// are baked in (validated, non-secret). The journald noise is dropped by the
// record_modifier allowlist; the loki output turns MESSAGE into the raw line
// (drop_single_key: raw) with low-cardinality labels and ident/pid as structured
// metadata. Proven against a real Loki 3.x during the POC.
func buildFluentBitConfig(p LokiShipParams) string {
	var b strings.Builder
	b.WriteString(`# Generated by Nexus — journald -> Loki (readable line + structured metadata).
# Do not edit by hand: overwritten on the next logs.configure_shipping.
service:
  flush: 5
  log_level: info
  http_server: on
  http_listen: 127.0.0.1
  http_port: 2020

pipeline:
  inputs:
    - name: systemd
      tag: journal.*
      read_from_tail: on
      strip_underscores: on

  filters:
    - name: record_modifier
      match: '*'
      Allowlist_key: MESSAGE
      Allowlist_key: HOSTNAME
      Allowlist_key: MACHINE_ID
      Allowlist_key: SYSTEMD_UNIT
      Allowlist_key: PRIORITY
      Allowlist_key: SYSLOG_IDENTIFIER
      Allowlist_key: PID

  outputs:
    - name: loki
      match: '*'
`)
	fmt.Fprintf(&b, "      host: %s\n      port: %s\n", p.Host, p.Port)
	if p.TLS {
		b.WriteString("      tls: on\n      tls.verify: on\n")
	} else {
		b.WriteString("      tls: off\n")
	}
	if p.Tenant != "" {
		fmt.Fprintf(&b, "      tenant_id: %s\n", p.Tenant)
	}
	b.WriteString(`      labels: job=nexus-fleet, host=$HOSTNAME, machine_id=$MACHINE_ID, unit=$SYSTEMD_UNIT, level=$PRIORITY
      structured_metadata: ident=$SYSLOG_IDENTIFIER, pid=$PID
      remove_keys: HOSTNAME, MACHINE_ID, SYSTEMD_UNIT, PRIORITY, SYSLOG_IDENTIFIER, PID
      drop_single_key: raw
      line_format: json
`)
	return b.String()
}
