package actions

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"
)

func init() {
	Register(&HardenFail2banAction{})
	Register(&EnableAutoUpdatesAction{})
	Register(&SetLoginBannerAction{})
	Register(&DisableCoreDumpsAction{})
	Register(&HardenLoginDefsAction{})
	Register(&HardenSysctlNetworkAction{})
}

// ── core dumps (KRNL-5820) ──
const nocoreLimitsPath = "/etc/security/limits.d/99-nexus-nocore.conf"
const coredumpSysctlPath = "/etc/sysctl.d/99-nexus-coredump.conf"
const nocoreConf = `# Generated by Nexus — disabling core dumps (KRNL-5820).
* hard core 0
* soft core 0
root hard core 0
`
const coredumpSysctl = `# Generated by Nexus — no core dump for setuid binaries (KRNL-5820).
fs.suid_dumpable = 0
`

// ── login.defs (AUTH-9230/9286/9328) ──
const loginDefsPath = "/etc/login.defs"

var loginDefsSettings = [][2]string{
	{"UMASK", "027"},
	{"PASS_MAX_DAYS", "90"},
	{"PASS_MIN_DAYS", "1"},
	{"PASS_WARN_AGE", "14"},
	{"SHA_CRYPT_MIN_ROUNDS", "640000"},
}

// Default legal banner (BANN-7126/7130) — overridable via the "text" param.
const loginBanner = `*** Restricted access - Nexus ***
Any unauthorized access to this system is prohibited and may be subject to
prosecution. All activity may be logged and monitored.
`

// ═══════════════════════════════════════════════════════════════
// "Install a utility" hardening remediations (Phase 2).
// Mutations: go through dispatchAction (RBAC + confirmation on the UI side).
// ═══════════════════════════════════════════════════════════════

const autoUpdatesConfPath = "/etc/apt/apt.conf.d/20auto-upgrades"

// jail.local: protects SSH by default, reads the systemd journal. The 3 values
// (bantime/findtime/maxretry) are configurable via the action params.
const fail2banJailTemplate = `# Generated by Nexus — basic anti-bruteforce protection.
[DEFAULT]
bantime  = %s
findtime = %s
maxretry = %s
backend  = systemd

[sshd]
enabled = true
`

// bantime/findtime: fail2ban duration (seconds or shorthand 600/10m/1h/1d/1w).
var fail2banDurationRe = regexp.MustCompile(`^\d+[smhdw]?$`)
var fail2banIntRe = regexp.MustCompile(`^\d+$`)

// paramStr reads a string parameter with a default value.
func paramStr(params map[string]interface{}, key, def string) string {
	if v, ok := params[key].(string); ok && strings.TrimSpace(v) != "" {
		return strings.TrimSpace(v)
	}
	return def
}

const autoUpdatesConf = `// Generated by Nexus — automatic security updates.
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
`

// ───────────────────────── fail2ban ─────────────────────────

type HardenFail2banAction struct{}

func (a *HardenFail2banAction) ID() string         { return "security.harden_fail2ban" }
func (a *HardenFail2banAction) Capability() string { return "security" }

func (a *HardenFail2banAction) Validate(params map[string]interface{}) error {
	for _, k := range []string{"bantime", "findtime"} {
		if v, ok := params[k].(string); ok && v != "" && !fail2banDurationRe.MatchString(v) {
			return fmt.Errorf("%s invalid (expected: 600, 10m, 1h, 1d…)", k)
		}
	}
	if v, ok := params["maxretry"].(string); ok && v != "" && !fail2banIntRe.MatchString(v) {
		return fmt.Errorf("maxretry invalid (integer expected)")
	}
	return nil
}

func (a *HardenFail2banAction) Execute(params map[string]interface{}) (interface{}, error) {
	// 1. Install if absent (whitelisted apt)
	if !fileExists("/usr/bin/fail2ban-client") {
		if err := sudoRun(nexusAgentBin, "privhelper", "pkg", "install", "fail2ban"); err != nil {
			return nil, fmt.Errorf("fail2ban installation: %w", err)
		}
	}

	// 2. Deploy jail.local (validated values → no config injection)
	jail := fmt.Sprintf(
		fail2banJailTemplate,
		paramStr(params, "bantime", "1h"),
		paramStr(params, "findtime", "10m"),
		paramStr(params, "maxretry", "5"),
	)
	if err := installRootFile(jail, "sec-fail2ban-*.tmp", "/etc/fail2ban/jail.local"); err != nil {
		return nil, err
	}

	// 3. Enable + (re)start
	if err := sudoRun(nexusAgentBin, "privhelper", "svc", "enable", "fail2ban"); err != nil {
		return nil, fmt.Errorf("enable fail2ban: %w", err)
	}
	if err := sudoRun(nexusAgentBin, "privhelper", "svc", "restart", "fail2ban"); err != nil {
		return nil, fmt.Errorf("restart fail2ban: %w", err)
	}

	return map[string]interface{}{
		"fail2ban_installed": true,
		"fail2ban_active":    systemctlActive("fail2ban"),
		"jail":               "/etc/fail2ban/jail.local",
	}, nil
}

// ──────────────────── unattended-upgrades ────────────────────

type EnableAutoUpdatesAction struct{}

func (a *EnableAutoUpdatesAction) ID() string                              { return "security.enable_auto_updates" }
func (a *EnableAutoUpdatesAction) Capability() string                      { return "security" }
func (a *EnableAutoUpdatesAction) Validate(_ map[string]interface{}) error { return nil }

func (a *EnableAutoUpdatesAction) Execute(params map[string]interface{}) (interface{}, error) {
	if isDryRun(params) {
		return dryRunChanges(
			"Installs unattended-upgrades if absent and enables the service.",
			[2]string{autoUpdatesConfPath, autoUpdatesConf},
		), nil
	}
	if !fileExists("/usr/bin/unattended-upgrade") && !fileExists("/usr/bin/unattended-upgrades") {
		if err := sudoRun(nexusAgentBin, "privhelper", "pkg", "install", "unattended-upgrades"); err != nil {
			return nil, fmt.Errorf("unattended-upgrades installation: %w", err)
		}
	}

	if err := installRootFile(autoUpdatesConf, "sec-autoupd-*.tmp", autoUpdatesConfPath); err != nil {
		return nil, err
	}

	// The service applies updates via the apt-daily timers; we enable it too.
	_ = sudoRun(nexusAgentBin, "privhelper", "svc", "enable", "unattended-upgrades")

	return map[string]interface{}{
		"auto_updates_active": autoUpdatesActive(),
		"config":              autoUpdatesConfPath,
	}, nil
}

// ──────────────────── legal banner ────────────────────

type SetLoginBannerAction struct{}

func (a *SetLoginBannerAction) ID() string         { return "security.set_login_banner" }
func (a *SetLoginBannerAction) Capability() string { return "security" }

func (a *SetLoginBannerAction) Validate(params map[string]interface{}) error {
	if t, ok := params["text"].(string); ok {
		if len(t) > 4096 {
			return fmt.Errorf("banner too long (max 4096 characters)")
		}
		if strings.ContainsRune(t, '\x00') {
			return fmt.Errorf("invalid banner (null character)")
		}
	}
	return nil
}

func (a *SetLoginBannerAction) Execute(params map[string]interface{}) (interface{}, error) {
	// Configurable text (param "text"); Nexus default if empty/absent.
	banner := loginBanner
	if t, ok := params["text"].(string); ok && strings.TrimSpace(t) != "" {
		banner = strings.TrimRight(t, "\n") + "\n"
	}
	// /etc/issue (local console) AND /etc/issue.net (network/SSH connections).
	if err := installRootFile(banner, "sec-banner-*.tmp", "/etc/issue"); err != nil {
		return nil, err
	}
	if err := installRootFile(banner, "sec-banner-*.tmp", "/etc/issue.net"); err != nil {
		return nil, err
	}
	return map[string]interface{}{
		"login_banner_set": true,
		"files":            []string{"/etc/issue", "/etc/issue.net"},
	}, nil
}

// loginBannerSet: a real banner is in place if /etc/issue contains substantial
// text (beyond the distro default like "Ubuntu 24.04 LTS \n \l").
// Content-independent heuristic (the text is configurable): we strip the \X
// escapes and the spaces, and require ≥ 40 useful characters.
func loginBannerSet() bool {
	data, err := os.ReadFile("/etc/issue")
	if err != nil {
		return false
	}
	stripped := regexp.MustCompile(`\\.`).ReplaceAllString(string(data), "")
	return len(strings.TrimSpace(stripped)) >= 40
}

// ──────────────────── core dumps ────────────────────

type DisableCoreDumpsAction struct{}

func (a *DisableCoreDumpsAction) ID() string                              { return "security.disable_core_dumps" }
func (a *DisableCoreDumpsAction) Capability() string                      { return "security" }
func (a *DisableCoreDumpsAction) Validate(_ map[string]interface{}) error { return nil }

func (a *DisableCoreDumpsAction) Execute(params map[string]interface{}) (interface{}, error) {
	if isDryRun(params) {
		return dryRunChanges(
			"Then `sysctl -p` for immediate application. No impact on services.",
			[2]string{nocoreLimitsPath, nocoreConf},
			[2]string{coredumpSysctlPath, coredumpSysctl},
		), nil
	}
	if err := installRootFile(nocoreConf, "sec-nocore-*.tmp", nocoreLimitsPath); err != nil {
		return nil, err
	}
	if err := installRootFile(coredumpSysctl, "sec-coredump-*.tmp", coredumpSysctlPath); err != nil {
		return nil, err
	}
	// Apply the sysctl immediately (the limits.d applies to new sessions).
	if err := sudoRun("/usr/sbin/sysctl", "-p", coredumpSysctlPath); err != nil {
		return nil, fmt.Errorf("sysctl -p: %w", err)
	}
	return map[string]interface{}{
		"core_dumps_disabled": true,
		"files":               []string{nocoreLimitsPath, coredumpSysctlPath},
	}, nil
}

func coreDumpsDisabled() bool {
	return fileExists(nocoreLimitsPath) && fileExists(coredumpSysctlPath)
}

// ──────────────────── login.defs ────────────────────

type HardenLoginDefsAction struct{}

func (a *HardenLoginDefsAction) ID() string                              { return "security.harden_login_defs" }
func (a *HardenLoginDefsAction) Capability() string                      { return "security" }
func (a *HardenLoginDefsAction) Validate(_ map[string]interface{}) error { return nil }

func (a *HardenLoginDefsAction) Execute(params map[string]interface{}) (interface{}, error) {
	if isDryRun(params) {
		var b strings.Builder
		for _, kv := range loginDefsSettings {
			fmt.Fprintf(&b, "%s\t%s\n", kv[0], kv[1])
		}
		return dryRunChanges(
			"In-place edit: only these directives are (re)written, the rest of /etc/login.defs is preserved. Affects only NEW accounts/passwords.",
			[2]string{loginDefsPath, b.String()},
		), nil
	}
	data, err := os.ReadFile(loginDefsPath) // world-readable
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", loginDefsPath, err)
	}
	content := string(data)
	for _, kv := range loginDefsSettings {
		content = setLoginDef(content, kv[0], kv[1])
	}
	if err := installRootFile(content, "sec-logindefs-*.tmp", loginDefsPath); err != nil {
		return nil, err
	}
	return map[string]interface{}{
		"login_defs_hardened": true,
		"applied":             loginDefsSettings,
	}, nil
}

// setLoginDef replaces (or adds) a KEY directive in the login.defs content.
// Idempotent: keeps the 1st occurrence (active or commented) rewritten to the
// correct value, removes any duplicates.
func setLoginDef(content, key, value string) string {
	re := regexp.MustCompile(`^[\t ]*#?[\t ]*` + regexp.QuoteMeta(key) + `([\t ]|=|$)`)
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines)+1)
	done := false
	for _, l := range lines {
		if re.MatchString(l) {
			if !done {
				out = append(out, key+"\t"+value)
				done = true
			}
			continue // removes duplicates
		}
		out = append(out, l)
	}
	if !done {
		out = append(out, key+"\t"+value)
	}
	return strings.Join(out, "\n")
}

func loginDefsHardened() bool {
	data, err := os.ReadFile(loginDefsPath)
	if err != nil {
		return false
	}
	return regexp.MustCompile(`(?m)^[\t ]*UMASK[\t ]+027\b`).Match(data)
}

// ──────────────────── network/kernel sysctl ────────────────────
// Conservative, safe defaults (Lynis NETW-*/KRNL-*, CIS). Deliberately EXCLUDES
// net.ipv4.conf.*.rp_filter: strict reverse-path filtering breaks legitimate
// asymmetric routing (multi-homed hosts, VPN gateways). Applied via `sysctl -e`
// so unknown keys (e.g. IPv6 disabled) are ignored instead of failing the action.
const networkSysctlPath = "/etc/sysctl.d/99-nexus-network.conf"
const networkSysctlConf = `# Generated by Nexus — network & kernel hardening (safe defaults; Lynis/CIS).
# TCP SYN flood protection.
net.ipv4.tcp_syncookies = 1
# Ignore ICMP redirects (host is not a router) — anti-MITM.
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
# Do not send ICMP redirects.
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
# Reject source-routed packets.
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0
# Log martian (spoofed / source-routed) packets.
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1
# Ignore broadcast pings and bogus ICMP error responses.
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1
# Kernel information-disclosure hardening.
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
# Filesystem link protections.
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
`

type HardenSysctlNetworkAction struct{}

func (a *HardenSysctlNetworkAction) ID() string                              { return "security.harden_sysctl_network" }
func (a *HardenSysctlNetworkAction) Capability() string                      { return "security" }
func (a *HardenSysctlNetworkAction) Validate(_ map[string]interface{}) error { return nil }

func (a *HardenSysctlNetworkAction) Execute(params map[string]interface{}) (interface{}, error) {
	if isDryRun(params) {
		return dryRunChanges(
			"Then `sysctl -e -p` for immediate application (unknown keys — e.g. IPv6 disabled — are ignored). No service impact. rp_filter is deliberately excluded to avoid breaking asymmetric routing.",
			[2]string{networkSysctlPath, networkSysctlConf},
		), nil
	}
	if err := installRootFile(networkSysctlConf, "sec-netsysctl-*.tmp", networkSysctlPath); err != nil {
		return nil, err
	}
	// -e: ignore errors about unknown keys (IPv6-disabled hosts lack net.ipv6.*).
	if err := sudoRun("/usr/sbin/sysctl", "-e", "-p", networkSysctlPath); err != nil {
		return nil, fmt.Errorf("sysctl -e -p: %w", err)
	}
	return map[string]interface{}{
		"sysctl_network_hardened": true,
		"file":                    networkSysctlPath,
	}, nil
}

func networkSysctlHardened() bool {
	return fileExists(networkSysctlPath)
}

// ───────────────────────── helpers ─────────────────────────

// dryRunChanges builds the uniform preview response: the list of files
// (and their exact content) that WOULD be written, without applying anything.
// Lets the UI show the details before confirmation, for all remediations.
func dryRunChanges(note string, changes ...[2]string) map[string]interface{} {
	list := make([]map[string]string, 0, len(changes))
	for _, c := range changes {
		list = append(list, map[string]string{"path": c[0], "content": c[1]})
	}
	return map[string]interface{}{"dry_run": true, "changes": list, "note": note}
}

func isDryRun(params map[string]interface{}) bool {
	dr, _ := params["dry_run"].(bool)
	return dr
}

// installRootFile writes the content to a tempfile (/var/lib/nexus-agent) then
// moves it as root via `sudo install` (fixed whitelisted destination path).
func installRootFile(content, tmpPattern, dest string) error {
	tmp, err := os.CreateTemp("/var/lib/nexus-agent", tmpPattern)
	if err != nil {
		return fmt.Errorf("tempfile: %w", err)
	}
	defer os.Remove(tmp.Name())
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return fmt.Errorf("write tempfile: %w", err)
	}
	tmp.Close()
	if err := sudoRun("/usr/bin/install", "-m", "644", "-o", "root", "-g", "root", tmp.Name(), dest); err != nil {
		return fmt.Errorf("install %s: %w", dest, err)
	}
	return nil
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

// systemctlActive returns true if the unit is active (is-active, no root).
func systemctlActive(unit string) bool {
	out, _ := exec.Command("systemctl", "is-active", unit).Output()
	return strings.TrimSpace(string(out)) == "active"
}

// autoUpdatesActive: the config file exists and enables Unattended-Upgrade.
func autoUpdatesActive() bool {
	data, err := os.ReadFile(autoUpdatesConfPath)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), `Unattended-Upgrade "1"`)
}
