package actions

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

func init() {
	Register(&SshHardenAction{})
}

// ═══════════════════════════════════════════════════════════════
// sshd.harden: applies a hardened sshd_config drop-in, with the
// watchdog-revert pattern IDENTICAL to firewall/netplan (snapshot -> mutation ->
// AfterFunc revert -> confirm WS -> dead-man's switch at boot).
//
// Anti-lock-out (mandatory):
//   1. `sshd -t` validates the config BEFORE any reload (abort if it fails).
//   2. Reload via SIGHUP to the sshd master (NOT `systemctl reload ssh`,
//      blocked in sudoers): does NOT cut existing sessions.
//   3. 120s watchdog: if not confirmed, the previous drop-in is restored.
// The drop-in does NOT touch PasswordAuthentication/PermitRootLogin (avoids
// involuntary lockout) — only modern algos + limits.
// ═══════════════════════════════════════════════════════════════

const (
	sshdWatchdogDuration = 120 * time.Second
	sshdDropinPath       = "/etc/ssh/sshd_config.d/99-nexus-hardening.conf"
	sshdDropinName       = "99-nexus-hardening.conf"
	sshdSnapshotPrefix   = "sshd-snapshot-"
)

const sshdHardeningDropin = `# Generated by Nexus — SSH hardening (modern algos + reasonable limits).
# Deliberately NOT modified here: PasswordAuthentication and PermitRootLogin,
# to avoid any involuntary lockout (to be hardened separately, knowingly).
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
MaxAuthTries 4
LoginGraceTime 30
X11Forwarding no
`

type PendingSshd struct {
	RequestID   string
	SnapshotDir string
	Timer       *time.Timer
	CreatedAt   time.Time
}

var (
	sshdMu        sync.Mutex
	pendingSshd   = map[string]*PendingSshd{}
	sshdReserving bool // in-flight reservation (closes the TOCTOU window)
)

// HandleSshdConfirm cancels the pending revert (confirmation received).
func HandleSshdConfirm(requestID string) {
	sshdMu.Lock()
	defer sshdMu.Unlock()
	p, ok := pendingSshd[requestID]
	if !ok {
		return
	}
	p.Timer.Stop()
	os.RemoveAll(p.SnapshotDir)
	delete(pendingSshd, requestID)
	log.Printf("[SSHd] Hardening confirmed for request_id=%s, snapshot discarded", requestID)
}

// RecoverPendingSshd is called at agent startup (dead-man's switch).
func RecoverPendingSshd() {
	entries, err := os.ReadDir(snapshotDir)
	if err != nil {
		return
	}
	for _, e := range entries {
		if !e.IsDir() || !strings.HasPrefix(e.Name(), sshdSnapshotPrefix) {
			continue
		}
		snapDir := filepath.Join(snapshotDir, e.Name())
		log.Printf("[SSHd] Recovering pending snapshot %s — reverting", snapDir)
		if err := restoreSshdFromSnapshot(snapDir); err != nil {
			log.Printf("[SSHd] Revert failed: %v", err)
		}
		os.RemoveAll(snapDir)
	}
}

// snapshotSshd copies the current drop-in (if it exists) into a dedicated tempdir.
// If the drop-in does not exist, the snapshot stays empty -> the restore will
// delete it (back to the "absent" state).
func snapshotSshd(requestID string) (string, error) {
	os.MkdirAll(snapshotDir, 0700)
	snapDir := filepath.Join(snapshotDir, sshdSnapshotPrefix+requestID)
	if err := os.MkdirAll(snapDir, 0700); err != nil {
		return "", err
	}
	if _, err := os.Stat(sshdDropinPath); err == nil {
		// sudo cat because the file may be root:root
		out, err := exec.Command("sudo", "-n", "/bin/cat", sshdDropinPath).Output()
		if err != nil {
			return "", fmt.Errorf("snapshot read: %w", err)
		}
		if err := os.WriteFile(filepath.Join(snapDir, sshdDropinName), out, 0600); err != nil {
			return "", err
		}
	}
	return snapDir, nil
}

// restoreSshdFromSnapshot restores the previous state: reinstalls the drop-in
// from the snapshot if it existed, otherwise removes the drop-in. Then reloads sshd.
func restoreSshdFromSnapshot(snapDir string) error {
	snapFile := filepath.Join(snapDir, sshdDropinName)
	if _, err := os.Stat(snapFile); err == nil {
		if err := sudoRun(nexusAgentBin, "privhelper", "install-sshd", snapFile); err != nil {
			return fmt.Errorf("restore install: %w", err)
		}
	} else {
		// The drop-in did not exist before -> remove it.
		if err := sudoRun("/bin/rm", "-f", sshdDropinPath); err != nil {
			return fmt.Errorf("restore rm: %w", err)
		}
	}
	return reloadSshd()
}

// registerPendingSshd snapshots + arms the 120s timer.
func registerPendingSshd(requestID string) (*PendingSshd, error) {
	sshdMu.Lock()
	if len(pendingSshd) > 0 || sshdReserving {
		sshdMu.Unlock()
		return nil, fmt.Errorf("another SSH hardening change is pending confirmation")
	}
	sshdReserving = true
	sshdMu.Unlock()

	snapDir, err := snapshotSshd(requestID)
	if err != nil {
		sshdMu.Lock()
		sshdReserving = false
		sshdMu.Unlock()
		return nil, err
	}

	p := &PendingSshd{RequestID: requestID, SnapshotDir: snapDir, CreatedAt: time.Now()}
	p.Timer = time.AfterFunc(sshdWatchdogDuration, func() {
		sshdMu.Lock()
		defer sshdMu.Unlock()
		if _, still := pendingSshd[requestID]; !still {
			return
		}
		log.Printf("[SSHd] Watchdog expired for request_id=%s — reverting", requestID)
		if err := restoreSshdFromSnapshot(p.SnapshotDir); err != nil {
			log.Printf("[SSHd] Revert failed: %v", err)
		}
		os.RemoveAll(p.SnapshotDir)
		delete(pendingSshd, requestID)
	})

	sshdMu.Lock()
	pendingSshd[requestID] = p
	sshdReserving = false
	sshdMu.Unlock()
	return p, nil
}

// reloadSshd reloads the sshd config via SIGHUP to the master (no interruption
// of ongoing sessions). `systemctl reload ssh` is deliberately refused (privhelper
// svc, AGENT-006: ssh/sshd protected against stop/restart/reload/disable).
func reloadSshd() error {
	pid := sshdMasterPID()
	if pid == "" {
		return fmt.Errorf("sshd master PID not found")
	}
	return sudoRun("/bin/kill", "-SIGHUP", pid)
}

func sshdMasterPID() string {
	if b, err := os.ReadFile("/run/sshd.pid"); err == nil {
		if p := strings.TrimSpace(string(b)); isNumeric(p) {
			return p
		}
	}
	out, err := exec.Command("/usr/bin/pidof", "sshd").Output()
	if err != nil {
		return ""
	}
	fields := strings.Fields(string(out))
	if len(fields) == 0 {
		return ""
	}
	// pidof lists from newest to oldest; the master is the oldest.
	last := fields[len(fields)-1]
	if !isNumeric(last) {
		return ""
	}
	return last
}

func isNumeric(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}

type SshHardenAction struct{}

func (a *SshHardenAction) ID() string                              { return "sshd.harden" }
func (a *SshHardenAction) Capability() string                      { return "security" }
func (a *SshHardenAction) Validate(_ map[string]interface{}) error { return nil }

func (a *SshHardenAction) Execute(params map[string]interface{}) (interface{}, error) {
	// Preview (dry-run): returns EXACTLY what would be written, without applying
	// anything (no snapshot/install/reload/watchdog). Lets the UI show the
	// content before the user confirms — single source = the agent (no risk of
	// divergence with text copied on the UI side).
	if dr, _ := params["dry_run"].(bool); dr {
		return map[string]interface{}{
			"dry_run":             true,
			"dropin":              sshdDropinPath,
			"content":             sshdHardeningDropin,
			"watchdog_expires_in": int(sshdWatchdogDuration.Seconds()),
		}, nil
	}

	reqID, _ := params["request_id"].(string)
	if reqID == "" {
		reqID = fmt.Sprintf("sshd-%d", time.Now().UnixNano())
	}

	// 1. Snapshot + arm the watchdog
	pr, err := registerPendingSshd(reqID)
	if err != nil {
		return nil, err
	}

	// 2. Write the hardened drop-in (tempfile + sudo install)
	tmp, err := os.CreateTemp(snapshotDir, "sshd-dropin-*.tmp")
	if err != nil {
		HandleSshdConfirm(reqID)
		return nil, fmt.Errorf("create temp: %w", err)
	}
	tmp.WriteString(sshdHardeningDropin)
	tmp.Close()
	defer os.Remove(tmp.Name())

	if err := sudoRun(nexusAgentBin, "privhelper", "install-sshd", tmp.Name()); err != nil {
		HandleSshdConfirm(reqID)
		return nil, fmt.Errorf("install drop-in: %w", err)
	}

	// 3. VALIDATE before any reload (anti-lock-out #1)
	if err := sudoRun("/usr/sbin/sshd", "-t"); err != nil {
		// Invalid config -> restore the previous state then cancel.
		_ = restoreSshdFromSnapshot(pr.SnapshotDir)
		HandleSshdConfirm(reqID)
		return nil, fmt.Errorf("sshd -t validation failed, drop-in reverted: %w", err)
	}

	// 4. Reload (SIGHUP master) — existing sessions preserved
	if err := reloadSshd(); err != nil {
		_ = restoreSshdFromSnapshot(pr.SnapshotDir)
		HandleSshdConfirm(reqID)
		return nil, fmt.Errorf("reload sshd failed: %w", err)
	}

	return map[string]interface{}{
		"applied":             true,
		"request_id":          reqID,
		"dropin":              sshdDropinPath,
		"watchdog_expires_in": int(sshdWatchdogDuration.Seconds()),
		"watchdog_expires_at": pr.CreatedAt.Add(sshdWatchdogDuration).Format(time.RFC3339),
	}, nil
}
